name: Auto Comment
on:
  issues:
  pull_request_target:
    types: [closed, opened]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 🚧　Install
        run: |
          yarn
      - name: 📦　Build
        run: |
          yarn build
      - uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          pullRequestMerged: >
            Thank you for your contributions @{{ author }} :partying_face:
            Join our [Discord](http://discord.gg/7jwZaa8WDr) to claim your contributors role (_if you haven't already_) and stay connected with us.
            Cheers!

          pullRequestOpened: >
            👋 @{{ author }}

            Thank you for raising your pull request.

            Please make sure you have followed our contributing guidelines. We will review it as soon as possible
