name: Auto Comment
on: [pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pullRequestMerged: |
            Thank you for your contributions @{{ author }} :partying_face:
            Join our [Discord](http://discord.gg/7jwZaa8WDr) to claim your contributors role.
            Cheers!
